export { default as CustomerReviews } from "./customer-reviews"
export { default as Hero } from "./hero"
export { default as Footer } from "./footer"
export { default as PopularProducts } from "./popular-products"
export { default as Services } from "./services"
export { default as SpecialOffer } from "./special-offer"
export { default as Subscribe  } from "./subscribe"
export { default as SuperQuality } from "./super-quality"